---
title: "Features with large post-pre logFC "
author: "Nate Olson"
date: '`r Sys.Date()`'
always_allow_html: yes
output:
  pdf_document: default
  html_document: default
---

```{r}
library(tidyverse)
```

```{r}
logFC_df <- readRDS("~/Desktop/logFC_edgeR_df.rds")
logFC_pre_post <- logFC_df %>% filter(T1 == 0, T2 == 20)
```

```{r}
ggplot(logFC_pre_post) + geom_point(aes(x = logCPM, y = logFC)) + facet_wrap(~pipe)
```

```{r}
logFC_pre_post %>% filter(logFC > 5, logCPM > 5) %>% 
      group_by(pipe, biosample_id) %>% 
      summarise(count = n())
```
```{r}
large_logFC <- logFC_pre_post %>% 
      filter(logFC > 5, logCPM > 5) %>% 
      rename(logFC_prepost = logFC ) %>% 
      ungroup() %>% 
      select(pipe, biosample_id, OTUname, logFC_prepost) %>%
      left_join(logFC_df)
```

## By Pipeline
### Unclustered
```{r warning = FALSE, message = FALSE}
large_logFC %>% 
      filter(T2 %in% c(1:5),pipe == "unclustered", T1 != 0, logCPM > 10) %>% 
      ggplot() + 
      geom_path(aes(y = logFC, x = as.numeric(as.character(T2)), group = OTUname)) + 
      geom_point(aes(y = logFC, x = as.numeric(as.character(T2)), size = logCPM), 
                 shape = 21, color = "grey60") + 
      geom_hline(aes(yintercept = 0), linetype = 2) +
      facet_grid(biosample_id ~ T1, scale = "free", space = "free_x") +
      theme_bw()
```

## DADA2
```{r warning = FALSE, message = FALSE}
large_logFC %>% 
      filter(T2 %in% c(1:5),pipe == "dada2", T1 != 0, logCPM > 10) %>% 
      ggplot() + 
      geom_path(aes(y = logFC, x = as.numeric(as.character(T2)), group = OTUname)) + 
      geom_point(aes(y = logFC, x = as.numeric(as.character(T2)), size = logCPM), 
                 shape = 21, color = "grey60") + 
      geom_hline(aes(yintercept = 0), linetype = 2) +
      facet_grid(biosample_id ~ T1, scale = "free", space = "free_x") +
      theme_bw()
```

## Mothur
```{r warning = FALSE, message = FALSE}
large_logFC %>% 
      filter(T2 %in% c(1:5),pipe == "mothur", T1 != 0, logCPM > 7) %>% 
      ggplot() + 
      geom_path(aes(y = logFC, x = as.numeric(as.character(T2)), group = OTUname)) + 
      geom_point(aes(y = logFC, x = as.numeric(as.character(T2)), size = logCPM), 
                 shape = 21, color = "grey60") + 
      geom_hline(aes(yintercept = 0), linetype = 2) +
      facet_grid(biosample_id ~ T1, scale = "free", space = "free_x") +
      theme_bw()
```


## QIIME
```{r warning = FALSE, message = FALSE}
large_logFC %>% 
      filter(T2 %in% c(1:5),pipe == "qiime", T1 != 0, logCPM > 7) %>% 
      ggplot() + 
      geom_path(aes(y = logFC, x = as.numeric(as.character(T2)), group = OTUname)) + 
      geom_point(aes(y = logFC, x = as.numeric(as.character(T2)), size = logCPM), 
                 shape = 21, color = "grey60") + 
      geom_hline(aes(yintercept = 0), linetype = 2) +
      facet_grid(biosample_id ~ T1, scale = "free", space = "free_x") +
      theme_bw()
```

