---
title: "The Good, the Bad, and the Ugly"
author: "Nate Olson"
date: '`r Sys.Date()`'
always_allow_html: yes
output:
  pdf_document: default
  html_document: default
---

```{r setup, warning=FALSE, message=FALSE, echo = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(ProjectTemplate)
cwd <- getwd()
setwd("../")
load.project()
setwd(cwd)
```

```{r echo = FALSE}
pipeline_dir <- "../../mgtst_pipelines"
mrexp <- get_mrexp(pipeline_dir)
```

```{r}
## Extracting a tidy dataframe with count values from MRexpiment objects
get_count_df <- function(mrobj, agg_genus = FALSE){
      if(agg_genus){
            mrobj <- aggregateByTaxonomy(mrobj, lvl = "Rank6", 
                                         norm = FALSE, log = FALSE, sl = 1)
      }
      
      mrobj <- cumNorm(mrobj, p = 0.75)
      mrobj %>%
            # not sure whether or not to normalize counts prior to analysis
            MRcounts(norm = TRUE, log = FALSE, sl = 1000) %>%  
            as.data.frame() %>% 
            rownames_to_column(var = "feature_id") %>% 
            gather("id","count", -feature_id)
}


get_rep_info <- function(count_df){
      count_replicate_df <- count_df %>% 
            mutate(detect = if_else(count > 1, 1, 0)) %>%
            group_by(pipe, biosample_id, titration, t_fctr, feature_id) %>% 
            summarise(total_detect = sum(detect),
                      n_replicates = n(),
                      avg_non0_count = sum(count)/total_detect) %>%
            mutate(detect_prop = total_detect/n_replicates) %>% 
            select(-total_detect) 
      
      count_replicate_df %>% ungroup() %>% 
      mutate(t_fctr = paste0("T",t_fctr)) %>% 
      select(pipe, biosample_id, feature_id, t_fctr, detect_prop) 
}


assign_cat <- function(rep_info){
      prop_summary <- rep_info %>% 
            group_by(pipe, biosample_id, feature_id) %>% 
            summarise(prop_max = max(detect_prop), 
                      prop_min = min(detect_prop), 
                      prop_sum = sum(detect_prop)) 
      
      unmix_prop <- rep_info %>% 
            filter(t_fctr %in% c("T0","T20")) %>% 
            spread(t_fctr, detect_prop)
      
      left_join(prop_summary, unmix_prop) %>% 
            mutate(cat_null = if_else(prop_max == 0, 1, 0),
                   cat_full = if_else(prop_min == 1, 1, 0),
                   cat_near_full = if_else(prop_min == 0.75, 1, 0),
                   cat_mix  = if_else(prop_max == 1 & T0 == 0 & T20 == 0, 1, 0),
                   ## Post prop 5 - expected at least three replicates for titrations 4, 5, 10, and 15 
                   ## Pre prop 3 - expected at least three replicates for titrations 1, 2, 3, and 4 
                   ## titration 4, is ~94% post
                   ## titration 4, is ~94% post
                   cat_pre  = if_else(T20 == 1 & T0 == 0 & prop_sum == 8, 1, 0),
                   cat_post = if_else(T0 == 1 & T20 == 0 & prop_sum == 8, 1, 0),
                   cat_none = if_else(cat_null + cat_full + cat_near_full + cat_mix + cat_pre + cat_post == 0, 1, 0))
}
```

### Feature Level Category Assignments
```{r}
count_df <- mrexp %>% map_df(get_count_df, .id = "pipe") %>% 
      left_join(pData(mrexp$dada2)) %>% 
      filter(biosample_id != "NTC")

#count_df
rep_info <- get_rep_info(count_df) 

#rep_info
feature_info <- assign_cat(rep_info)

feature_cat <- feature_info %>% 
      select(-prop_max, -prop_min, -prop_sum, -T0, -T20) %>% 
      gather(cat, value, -pipe, -biosample_id, -feature_id) %>% 
      filter(value == 1) %>% select(-value) 
    
feature_cat %>% saveRDS("../data/feature_categories_df.rds")
```
```

```{r}
count_exp_df
```

