---
title: "logFC Post Specific Features"
author: "Nate Olson"
date: '`r Sys.Date()`'
always_allow_html: yes
output:
  pdf_document: default
  html_document: default
---

* Post-specific features are trouble some 
      * Plot raw counts vs. seq depth coloring by titration for post-specific 1-3 comparison  
```{r}
library(tidyverse)
library(forcats)
count_df <- readRDS("~/Desktop/raw_counts.RDS") %>%  
      group_by(id) %>% 
      mutate(total_count = sum(count))

nb_dada_counts <- readRDS("~/Desktop/nb_counts_dada2_titration.RDS")
pa_summary_anno_df <- readRDS("~/Desktop/pa_summary_anno_df.RDS")
```

### DADA2
Only four features are post-specific and present in titrations for E01JH0011.

```{r}
pa_post <- pa_summary_anno_df %>% 
      filter(pipe == "dada2", 
             # biosample_id == "E01JH0011", 
             T00 == 4, T20 == 0, pa_mixed != 0)

pa_post %>% group_by(biosample_id) %>% summarise(count = n())
```

```{r}
## Post specific features present in titrations
pa_11_post <- pa_summary_anno_df %>% 
      filter(pipe == "dada2", 
             biosample_id == "E01JH0011",
             T00 == 4, T20 == 0, pa_mixed != 0)

counts_post_11 <- count_df %>% 
      right_join(pa_11_post) %>% 
      filter(t_fctr %in% c(1,3))

## Annotating with negative binomial proportion
post_prop <- nb_dada_counts  %>% 
      filter(t_fctr == 0) %>% 
      right_join(pa_11_post) %>% 
      select(pipe, biosample_id, feature_id, nb_prop)

counts_post_11_features <- post_prop %>% 
      right_join(counts_post_11) %>%  
      ungroup() %>% 
      mutate(feature_id = fct_reorder(feature_id, nb_prop)) 
```

```{r}
counts_post_11_features %>% 
      group_by(feature_id) %>% 
      mutate(count_sum = median(count)) %>% 
      filter(count_sum > 0) %>% 
      ggplot() + geom_point(aes(x = total_count, y = count, 
                                color = t_fctr, shape = biosample_id)) + 
      facet_wrap(~feature_id, scale = "free_y") + theme_bw()
```

## Unclustered
```{r}
pa_post <- pa_summary_anno_df %>% 
      filter(pipe == "unclustered", 
             # biosample_id == "E01JH0011", 
             T00 == 4, T20 == 0, pa_mixed != 0)

pa_post %>% group_by(biosample_id) %>% summarise(count = n())
```

```{r}
pa_summary_anno_df$pipe %>% unique()
```

```{r}
nb_unclustered_counts <- readRDS("~/Desktop/nb_counts_unclustered_titration.RDS")
pa_11_post <- pa_summary_anno_df %>% 
      filter(pipe == "unclustered", 
             # biosample_id == "E01JH0011", 
             T00 == 4, T20 == 0)

counts_post_11 <- count_df %>% 
      right_join(pa_11_post) %>% 
      filter(t_fctr %in% c(1,3))

## Annotating with negative binomial proportion
post_prop <- nb_unclustered_counts  %>% 
      filter(t_fctr == 0) %>% 
      right_join(pa_11_post) %>% 
      select(pipe, biosample_id, feature_id, nb_prop) %>% 
      ungroup() %>% 
      top_n(10, nb_prop)

counts_post_11_features <- post_prop %>% 
      left_join(counts_post_11) %>%  
      ungroup() %>%
      mutate(feature_id = fct_reorder(feature_id, nb_prop))
```

```{r }
counts_post_11_features %>% 
      group_by(feature_id) %>% 
      mutate(count_sum = median(count)) %>% 
      filter(count_sum > 0) %>% 
      ggplot() + geom_point(aes(x = total_count, y = count, color = t_fctr)) + 
      facet_wrap(~feature_id* biosample_id, scale = "free_y", ncol = 4) + theme_bw()
```