---
title: "Raw Counts Data Frame NIST2"
author: "Nate Olson"
date: '`r Sys.Date()`'
always_allow_html: yes
output:
  pdf_document: default
  html_document: default
---

```{r message = FALSE}
library(ProjectTemplate)
cwd <- getwd()
setwd("../")
load.project()
setwd(cwd)
pipeline_dir <- "../../mgtst_runs/nist2" 

get_mrexp <- function(pipelines_dir){
      mrexp_files <- list(
            dada2 = file.path(pipeline_dir, "dada2/dada_mrexp.rds"),
            mothur =  file.path(pipeline_dir, "mothur/mothur_mrexp.rds"),
            qiime =  file.path(pipeline_dir, "qiime/qiime_mrexp.rds")
      )
      
      mrexp_files %>% map(readRDS)
}
mrexp <- get_mrexp(pipeline_dir)
```

## Objective 
Generate a tidy dataframe with count data.


```{r}
get_count_df <- function(mrobj, agg_genus = FALSE, css = TRUE){
      if(agg_genus){
            mrobj <- aggregateByTaxonomy(mrobj, lvl = "Rank6", 
                                         norm = FALSE, log = FALSE, sl = 1)
      }
      
      if(css == TRUE){
            mrobj <- cumNorm(mrobj, p = 0.75)
            count_mat <- MRcounts(mrobj, norm = TRUE, log = FALSE, sl = 1000)
      }else{
            count_mat <- MRcounts(mrobj, norm = FALSE, log = FALSE, sl = 1)
      }
       count_mat %>%  
            as.data.frame() %>% 
            rownames_to_column(var = "feature_id") %>% 
            gather("id","count", -feature_id)
}

## Converting count matrix to data frame
counts_df <- mrexp %>% 
      map_df(get_count_df, css = FALSE, .id = "pipe") %>% 
      ## Adding sample metadata
      left_join(pData(mrexp$dada2)) 
```

```{r}
saveRDS(counts_df, "~/Desktop/nist2_raw_counts.RDS")
```

