---
title: "Generate Phyloseq Object from Mothur Output"
author: "Nate Olson"
date: '`r Sys.Date()`'
output:
  pdf_document: default
  html_document: default
---

```{r setup, message = FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ProjectTemplate)
cwd <- getwd()
setwd("../")
load.project()
setwd(cwd)
library(phyloseq)
```

Loading mothur results
```{r}
mothur_dir <- "~/Projects/16S_etec_mix_study/analysis/pipelines/mothur/data/process/"
file_root <- "mgtst.trim.contigs.good.unique.good.filter.unique.precluster.pick"
shared_file <- file.path(mothur_dir, 
                         paste0(file_root, ".an.unique_list.shared"))
contax_file <- file.path(mothur_dir, 
                         paste0(file_root, ".an.unique_list.0.03.cons.taxonomy"))
ps_mothur <- import_mothur(mothur_shared_file = shared_file, 
                           mothur_constaxonomy_file = contax_file)
```

sample metadata
```{r}
sample_sheet <- sampleSheet %>% 
      unite(col = sample_name, pcr_16S_plate, pos, sep = "-", remove = F) %>% 
      filter(barcode_lab == "JHU", seq_lab == "JHU") %>% as.data.frame() %>% 
      ## adding variables for consistency with other phyloseq objects
      mutate(dilution = if_else(titration == 20, -1, titration),
             sampleID = biosample_id)
rownames(sample_sheet) <- sample_sheet$sample_name
```

```{r}
sample_data(ps_mothur) <- sample_sheet
```

```{r}
ps_mothur
```

```{r}
saveRDS(ps_mothur, file = "../data/phyloseq_mothur.RDS")
```


