---
title: "96 well plate PCR layout"
author: "Nate Olson"
date: '`r Sys.Date()`'
output:
  pdf_document: default
  html_document: default
---

```{r setup, message = FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

96 Well plate layout for 16S rRNA PCR, library preparation, and sequencing. Titration factor 20 is used to represent the undiluted pre-treatment samples.

```{r}
make_plan_a_96_df <- function(sampleID, dilution){
    ## experimental design for 96 sample layout
    bio_replicates <- rep(sampleID,each = 2*length(dilution))
    dilution_96 <- rep(dilution, times = 2*length(sampleID))
    
    ntc <- data_frame(sampleID = rep("NTC",6),
                      sample_type = "control", dilution = NA)
    
    data_frame(sampleID = bio_replicates, 
                sample_type = "titration", dilution = dilution_96) %>% 
        bind_rows(ntc) %>% mutate(sample_type = ifelse(dilution %in% c(0,-1), 
                                                       "unmixed",sample_type)) ->df_96
}

make_plan_a_df <- function(sampleID, dilution){
    ## PCRs
    plate_1 <- make_plan_a_96_df(sampleID, dilution) %>% 
        mutate(pcr_16S_plate = 1, pcr_16S_id = 1:n())
    plate_2 <- make_plan_a_96_df(sampleID, dilution) %>% 
        mutate(pcr_16S_plate = 2, pcr_16S_id = (n() + 1):(2*n()))
    pcr_plates <- bind_rows(plate_1, plate_2) 
    
    ## Barcode
    barcode_jhu <- pcr_plates %>% mutate(barcode_lab = "JHU", 
                                          barcode_id = 1:n())
    barcode_nist <- pcr_plates %>% mutate(barcode_lab = "NIST", 
                                          barcode_id = (n() + 1):(2*n()))
    seq_plates <- bind_rows(barcode_jhu, barcode_nist)

    seq_jhu <- seq_plates %>% mutate(seq_lab = "JHU")
    seq_nist <- seq_plates %>% mutate(seq_lab = "NIST")
    return(list(pcr_sample_sheet = pcr_plates, 
                seq_sample_sheet = bind_rows(seq_jhu, seq_nist)))
}

sampleID <- c("E01JH0004","E01JH0011","E01JH0016","E01JH0017","E01JH0038")
dilution <- c(0,20,1:4,5,10,15)
plan_a_sample_sheets <- make_plan_a_df(sampleID, dilution)
plan_a_pcr <- plan_a_sample_sheets$pcr_sample_sheet
```


```{r}
pcr_plate_layout<- plan_a_pcr %>% 
    filter(pcr_16S_plate == 1, dilution != 0 | is.na(dilution)) %>% 
    mutate(half = c(rep(c(rep(0,8),rep(6,8)),5),rep(c(0,6), each = 3)), 
           col = half + as.numeric(factor(sampleID)), 
           row = c(rep(c("A","B","C","D","E","F","G","H"),10),
                   rep(c("A","D","H"), 2)))
pcr_plate_layout <- plan_a_pcr %>% filter(pcr_16S_plate == 1, dilution == 0) %>% 
    mutate(col = rep(c(6,12), 5), row = rep(c("F","B","C","E","G"),each = 2)) %>%
    bind_rows(pcr_plate_layout)

pcr_plate_layout %>% mutate(Row = as.numeric(factor(row))) %>% 
 ggplot(aes(x=col, y=Row)) +
    geom_point(data=expand.grid(seq(1,12), seq(1,8)), aes(x=Var1, y=Var2), 
               color='grey90', fill='white', shape=21, size=6) +
    geom_point(aes(color = sampleID), size=10) +
    geom_text(aes(label = dilution)) +
    coord_fixed(ratio=(13/12)/(9/8), xlim=c(0.5,12.5), ylim=c(0.5,8.5)) +
    scale_y_reverse(breaks=seq(1,8), labels=LETTERS[1:8]) +
    scale_x_continuous(breaks=seq(1,12)) +
    labs(title="PCR Layout") +
    theme_bw()
```

```{r}
ggsave("../img/pcr_plate_16S.png")
```

