---
title: "Untitled"
author: "Nate Olson"
date: "7/18/2017"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
feature_id <- LETTERS[1:4]
Pre <- c(0.5, 0, 0.20, 0.3)
Post <- c(0, 0.2, 0.5, 0.3)
## Prop bacterial DNA in unmixed Pre = 0.25, unmixed Post = 0.5
rho <- 0.5/0.75 ## post is 2X more bacterial DNA
Pre_bac <- 0.25
Post_bac <- 0.5

demo_dat <- data_frame(feature_id, Pre, Post) %>% 
      mutate(T1 = 2^-1 * Post + (1-(2^-1)) * Pre,
             T2 = 2^-2 * Post + (1-(2^-2)) * Pre,
             T3 = 2^-3 * Post + (1-(2^-3)) * Pre,
             T4 = 2^-4 * Post + (1-(2^-4)) * Pre,) %>% 
      gather("titration", "prop", -feature_id) %>% 
      mutate(count = prop * 100, 
             titration = factor(titration, 
                                levels = c("Post","T1","T2","T3","T4","Pre")),
             t_num = as.numeric(titration))

demo_bac_dat <- data_frame(feature_id, Pre, Post, Pre_bac, Post_bac) %>% 
      mutate(T1 = 2^-1 * Post_bac * Post + (1-(2^-1)) * Pre_bac * Pre,
             T2 = 2^-2 * Post_bac * Post + (1-(2^-2)) * Pre_bac * Pre,
             T3 = 2^-3 * Post_bac * Post + (1-(2^-3)) * Pre_bac * Pre,
             T4 = 2^-4 * Post_bac * Post + (1-(2^-4)) * Pre_bac * Pre) %>% 
      select(-Pre_bac, -Post_bac) %>% 
      gather("titration", "prop", -feature_id) %>% 
      group_by(titration) %>% 
      
      mutate(count = prop * 100, total_count = sum(count)) %>% 
      ungroup() %>% 
      mutate(prop = if_else(titration %in% paste0("T",1:4), count/total_count, prop),
             titration = factor(titration, 
                                levels = c("Post","T1","T2","T3","T4","Pre")),
             t_num = as.numeric(titration))
```

```{r}
demo_dat %>% mutate(prop = if_else(titration %in% c("Pre","Post"),prop, 0)) %>%  
    ggplot() + 
      geom_bar(aes(x = titration, y = prop, fill = feature_id), 
               stat = "identity") + 
      theme_bw() + facet_wrap(~feature_id, ncol = 1) + 
      labs(x = "Titration", y = "Relative Abundance") + 
      theme(legend.position = "none")
```


```{r}
ggplot(demo_dat) + 
      geom_bar(aes(x = titration, y = prop, fill = feature_id), 
               stat = "identity") + 
      theme_bw() + facet_wrap(~feature_id, ncol = 1) + 
      labs(x = "Titration", y = "Relative Abundance") + 
      theme(legend.position = "none")
```


```{r}
ggplot(demo_dat) + 
      geom_bar(aes(x = titration, y = prop, fill = feature_id), 
               stat = "identity") + 
      geom_line(data = demo_bac_dat, aes(x = as.numeric(t_num), y = prop)) +
      geom_point(data = demo_bac_dat, aes(x = titration, y =prop)) +
      theme_bw() + facet_wrap(~feature_id, ncol = 1) + 
      labs(x = "Titration", y = "Relative Abundance") + 
      theme(legend.position = "none")
```

```{r}
ggplot(demo_bac_dat) + geom_bar(aes(x = titration, y = prop, fill = feature_id), stat = "identity")
```



```{r}
demo_dat
```


Ecoli example
```{r}
dada_mrexp <- readRDS("~/Projects/mgtst_pipelines/dada2/dada_mrexp.rds")
total_abu <- dada_mrexp %>% colSums()
dada_pdata <- pData(dada_mrexp) %>% add_column(total_abu)
count_mat <- dada_mrexp@assayData$counts
count_df <- count_mat %>% as.data.frame() %>% rownames_to_column(var = "feature_id") %>% 
      gather("id","count", -feature_id)
dada_count <- dada_pdata %>% 
      left_join(count_df) %>% 
      mutate(t_fctr = paste0("T",t_fctr)) 

dada_ecoli <- dada_count %>% filter(feature_id == "SV1", biosample_id != "NTC") %>%
      mutate(t_fctr = factor(t_fctr, levels = paste0("T",c(0:5, 10, 15, 20))))
```


```{r}
mothur_mrexp <- readRDS("~/Projects/mgtst_pipelines/mothur/mothur_mrexp.rds")
total_abu <- mothur_mrexp %>% colSums()
mothur_pdata <- pData(mothur_mrexp) %>% add_column(total_abu)
count_mat <- mothur_mrexp@assayData$counts
count_df <- count_mat %>% as.data.frame() %>% rownames_to_column(var = "feature_id") %>% 
      gather("id","count", -feature_id)
mothur_count <- mothur_pdata %>% 
      left_join(count_df) %>% 
      mutate(t_fctr = paste0("T",t_fctr)) 

mothur_ecoli <- mothur_count %>% filter(feature_id == "Otu00001", biosample_id != "NTC") %>%
      mutate(t_fctr = factor(t_fctr, levels = paste0("T",c(0:5, 10, 15, 20))))
```

## QIIME E coli
```{r}
qiime_mrexp <- readRDS("~/Projects/mgtst_pipelines/qiime/qiime_mrexp.rds")
fData(qiime_mrexp) %>% filter(Rank6 == "g__Escherichia")
```

```{r}
qiime_entero_otus <- fData(qiime_mrexp) %>% filter(Rank5 == "f__Enterobacteriaceae") %>% .$OTUname
```


```{r}
fData(qiime_mrexp) %>% filter(OTUname == "782953")
```

```{r}
count_nb <- readRDS("~/Projects/mgtst_pub/data/nb_expected_eo_metric_feature_update_df.rds") %>% 
    mutate(count_post = post * total_abu, count_pre = pre * total_abu)
```


```{r}
count_nb %>% mutate(prop = count/total_abu) %>% 
      filter(feature_id == "SV1", biosample_id == "E01JH0011") %>% 
      ggplot() + 
      geom_point(aes(x = titration, y = prop)) + 
      geom_line(aes(x = titration, y = exp_prop)) + 
      theme_bw() + labs(y = "Relative Abundance", x = "Titration")
```


```{r}
count_nb %>% mutate(prop = count/total_abu) %>% 
      filter(feature_id %in% c("SV1","Otu00001","782953")) %>% 
      ggplot() + 
      geom_point(aes(x = titration, y = prop)) + 
      geom_line(aes(x = titration, y = exp_prop), color = "darkblue") + 
      facet_grid(pipe~biosample_id) +
      theme_bw() + labs(y = "Relative Abundance", x = "Titration")
```


```{r}
count_nb %>% mutate(prop = count/total_abu) %>% 
      filter(feature_id %in% c("744023", "114510","New.CleanUp.ReferenceOTU7975")) %>% 
      ggplot() + 
      geom_point(aes(x = titration, y = prop)) + 
      geom_line(aes(x = titration, y = exp_prop)) + 
      facet_grid(biosample_id~feature_id, scales = "free_y") +
      theme_bw() + labs(y = "Relative Abundance", x = "Titration")
```

```{r}
count_nb %>% mutate(prop = count/total_abu) %>% 
      filter(feature_id %in% c("744023", "114510","New.CleanUp.ReferenceOTU7975")) %>% 
    group_by(pipe, biosample_id, id, pcr_rep,t_fctr) %>% 
    summarise(feature_count = sum(count))
```

## Using theta estimates
```{r}
boot_theta_hat <- readRDS("~/Projects/mgtst_pub/data/bootstrap_theta_estimates.rds")
```

```{r}
boot_theta_hat
```

```{r}
count_nb_inferred <- boot_theta_hat %>% ungroup() %>%
    mutate(t_fctr = factor(t_fctr, levels = c(1:5, 10, 15))) %>% 
    select(pipe, biosample_id, theta_hat_mean, t_fctr) %>% 
    right_join(count_nb) %>% 
    mutate(inferred_prop = post * theta_hat_mean + pre * (1-theta_hat_mean))
```


```{r}
count_nb_inferred %>% mutate(prop = count/total_abu) %>% 
      filter(feature_id %in% c("SV1","Otu00001","782953")) %>% 
      ggplot() + 
      geom_point(aes(x = titration, y = prop)) + 
    geom_line(aes(x = titration, y = exp_prop), color = "darkblue") + 
      geom_line(aes(x = titration, y = inferred_prop), color = "darkorange") + 
      facet_grid(pipe~biosample_id) +
      theme_bw() + labs(y = "Relative Abundance", x = "Titration")
```






```{r}
count_nb_inferred %>% mutate(prop = count/total_abu) %>% 
      filter(feature_id %in% c("SV2","Otu00002")) %>% 
      ggplot() + 
      geom_point(aes(x = titration, y = prop)) + 
    geom_line(aes(x = titration, y = exp_prop), color = "darkblue") + 
      geom_line(aes(x = titration, y = inferred_prop), color = "darkorange") + 
      facet_grid(pipe~biosample_id) +
      theme_bw() + labs(y = "Relative Abundance", x = "Titration")
```


```{r}
count_nb_inferred %>% mutate(prop = count/total_abu) %>% 
      filter(feature_id %in% paste0("SV",2:10)) %>% 
      ggplot() + 
      geom_point(aes(x = titration, y = prop)) + 
    geom_line(aes(x = titration, y = exp_prop), color = "darkblue") + 
      geom_line(aes(x = titration, y = inferred_prop), color = "darkorange") + 
      facet_grid(feature_id~biosample_id) +
      theme_bw() + labs(y = "Relative Abundance", x = "Titration")
```

```{r}
count_nb_inferred %>% mutate(prop = count/total_abu) %>% 
      filter(feature_id %in% paste0("SV",9), biosample_id %in% c("E01JH0004", "E01JH0017")) %>% 
      ggplot() + 
      geom_point(aes(x = titration, y = prop)) + 
    geom_line(aes(x = titration, y = exp_prop), color = "darkblue") + 
      geom_line(aes(x = titration, y = inferred_prop), color = "darkorange") + 
      facet_grid(feature_id~biosample_id) +
      theme_bw() + labs(y = "Relative Abundance", x = "Titration")
```

```{r}
count_nb_inferred %>% mutate(prop = count/total_abu) %>% 
      filter(feature_id %in% paste0("SV",1:9), biosample_id %in% c("E01JH0004", "E01JH0017")) %>% 
      ggplot() + 
      geom_point(aes(x = titration, y = prop)) + 
    geom_line(aes(x = titration, y = exp_prop), color = "darkblue") + 
      geom_line(aes(x = titration, y = inferred_prop), color = "darkorange") + 
      facet_grid(feature_id~biosample_id) +
      theme_bw() + labs(y = "Relative Abundance", x = "Titration")
```


```{r}
count_nb_inferred %>% mutate(prop = count/total_abu) %>% 
      filter((feature_id %in% paste0("Otu0000",5) & biosample_id == "E01JH0016") |
                 (feature_id %in% paste0("SV",9) & biosample_id %in% c("E01JH0004", "E01JH0017"))) %>% 
      ggplot() + 
      geom_point(aes(x = titration, y = prop)) + 
    geom_line(aes(x = titration, y = exp_prop), color = "darkblue") + 
      geom_line(aes(x = titration, y = inferred_prop), color = "darkorange") + 
      facet_wrap(biosample_id~ feature_id) +
      theme_bw() + labs(y = "Relative Abundance", x = "Titration")
```

```{r}
qiime_entero_inferred <- count_nb_inferred %>% mutate(prop = count/total_abu) %>% 
      filter(feature_id %in% qiime_entero_otus) %>% 
    group_by(feature_id) %>% mutate(total_prop = sum(prop))
qiime_entero_inferred$total_prop %>% summary()

qiime_entero_inferred %>% filter(total_prop > 0.02) %>% 
ggplot() + 
      geom_point(aes(x = titration, y = prop)) + 
    geom_line(aes(x = titration, y = exp_prop), color = "darkblue") + 
      geom_line(aes(x = titration, y = inferred_prop), color = "darkorange") + 
      facet_grid(feature_id~biosample_id, scales = "free_y") +
      theme_bw() + labs(y = "Relative Abundance", x = "Titration")
```


#### Lots of features
```{r}
rel_abu_error <- count_nb_inferred %>% mutate(prop = count/total_abu,
                             inferred_error = prop - inferred_prop,
                             exp_error = prop - exp_prop,
                             inferred_error_rate = abs(inferred_error)/inferred_prop,
                             exp_error_rate = abs(exp_error)/exp_prop) 
```

```{r}
rel_abu_error %>% 
    filter(prop != 0) %>% 
    ggplot() + geom_boxplot(aes(x = pipe, y = inferred_error, color = biosample_id))
```

```{r}
rel_abu_error %>% 
    filter(prop != 0) %>% 
    ggplot() + geom_boxplot(aes(x = pipe, y = inferred_error_rate, color = biosample_id))
```

```{r}
rel_abu_error_summary <-rel_abu_error %>% 
    group_by(pipe, biosample_id,feature_id) %>% 
    summarise(med_inf_error_rate = median(inferred_error_rate),
              med_exp_error_rate = median(exp_error_rate))
```

```{r}
rel_abu_error_summary %>% #filter(med_inf_error_rate < 10) %>% 
    ggplot() + geom_boxplot(aes(x = pipe, y = med_inf_error_rate, color = biosample_id))
```

```{r}
rel_abu_error_summary %>% filter(med_inf_error_rate < 10) %>% 
    ggplot() + geom_boxplot(aes(x = pipe, y = med_inf_error_rate, color = biosample_id))
```



Next steps look into features with high med_inf_error_rates
```{r}
rel_abu_error_summary %>% filter(med_inf_error_rate > 150, med_inf_error_rate != Inf)
```

```{r}
count_nb_inferred %>% mutate(prop = count/total_abu) %>% 
      filter(biosample_id == "E01JH0016", feature_id %in% c("Otu00067","470382","696563","New.ReferenceOTU20")) %>% 
      ggplot() + 
      geom_point(aes(x = titration, y = prop)) + 
    geom_line(aes(x = titration, y = exp_prop), color = "darkblue") + 
      geom_line(aes(x = titration, y = inferred_prop), color = "darkorange") + 
      facet_wrap(biosample_id~ feature_id) +
      theme_bw() + labs(y = "Relative Abundance", x = "Titration")
```

```{r}
rel_abu_error_summary %>% filter(med_inf_error_rate < 150, med_inf_error_rate > 75, med_inf_error_rate != Inf)
```

```{r}
otu_set <- rel_abu_error_summary %>% filter(med_inf_error_rate < 150, 
                                            med_inf_error_rate > 75, 
                                            med_inf_error_rate != Inf)
```

```{r}
count_nb_inferred %>% mutate(prop = count/total_abu) %>% 
    right_join(otu_set) %>% 
      ggplot() + 
      geom_point(aes(x = titration, y = prop)) + 
    geom_line(aes(x = titration, y = exp_prop), color = "darkblue") + 
      geom_line(aes(x = titration, y = inferred_prop), color = "darkorange") + 
      facet_wrap(~feature_id, scales = "free_y") +
      theme_bw() + labs(y = "Relative Abundance", x = "Titration")
```

```{r}
otu_set <- rel_abu_error_summary %>% filter(med_inf_error_rate < 75, 
                                            med_inf_error_rate > 35, 
                                            med_inf_error_rate != Inf)
nrow(otu_set)
```


```{r}
count_nb_inferred %>% mutate(prop = count/total_abu) %>% 
    right_join(otu_set) %>% 
      ggplot() + 
      geom_point(aes(x = titration, y = prop)) + 
    geom_line(aes(x = titration, y = exp_prop), color = "darkblue") + 
      geom_line(aes(x = titration, y = inferred_prop), color = "darkorange") + 
      facet_wrap(~feature_id, scales = "free_y") +
      theme_bw() + labs(y = "Relative Abundance", x = "Titration")
```

```{r}
otu_set <- rel_abu_error_summary %>% filter(med_inf_error_rate < 35, 
                                            med_inf_error_rate > 20, 
                                            med_inf_error_rate != Inf)
nrow(otu_set)
```

```{r}
count_nb_inferred %>% mutate(prop = count/total_abu) %>% 
    right_join(otu_set) %>% 
      ggplot() + 
      geom_point(aes(x = titration, y = prop)) + 
    geom_line(aes(x = titration, y = exp_prop), color = "darkblue") + 
      geom_line(aes(x = titration, y = inferred_prop), color = "darkorange") + 
      facet_wrap(~feature_id, scales = "free_y") +
      theme_bw() + labs(y = "Relative Abundance", x = "Titration")
```

```{r}
otu_set <- rel_abu_error_summary %>% filter(med_inf_error_rate < 20, 
                                            med_inf_error_rate > 15, 
                                            med_inf_error_rate != Inf)
nrow(otu_set)
```

```{r}
count_nb_inferred %>% mutate(prop = count/total_abu) %>% 
    right_join(otu_set) %>% 
      ggplot() + 
      geom_point(aes(x = titration, y = prop)) + 
    geom_line(aes(x = titration, y = exp_prop), color = "darkblue") + 
      geom_line(aes(x = titration, y = inferred_prop), color = "darkorange") + 
      facet_wrap(~feature_id, scales = "free_y") +
      theme_bw() + labs(y = "Relative Abundance", x = "Titration")
```

```{r}
otu_set <- rel_abu_error_summary %>% filter(med_inf_error_rate < 15, 
                                            med_inf_error_rate > 12, 
                                            med_inf_error_rate != Inf)
nrow(otu_set)
```

```{r}
count_nb_inferred %>% mutate(prop = count/total_abu) %>% 
    right_join(otu_set) %>% 
      ggplot() + 
      geom_point(aes(x = titration, y = prop)) + 
    geom_line(aes(x = titration, y = exp_prop), color = "darkblue") + 
      geom_line(aes(x = titration, y = inferred_prop), color = "darkorange") + 
      facet_wrap(~feature_id, scales = "free_y") +
      theme_bw() + labs(y = "Relative Abundance", x = "Titration")
```

```{r}
otu_set <- rel_abu_error_summary %>% filter(med_inf_error_rate < 12, 
                                            med_inf_error_rate > 10, 
                                            med_inf_error_rate != Inf)
nrow(otu_set)
```

```{r}
count_nb_inferred %>% mutate(prop = count/total_abu) %>% 
    right_join(otu_set) %>% 
      ggplot() + 
      geom_point(aes(x = titration, y = prop)) + 
    geom_line(aes(x = titration, y = exp_prop), color = "darkblue") + 
      geom_line(aes(x = titration, y = inferred_prop), color = "darkorange") + 
      facet_wrap(~feature_id, scales = "free_y") +
      theme_bw() + labs(y = "Relative Abundance", x = "Titration")
```


```{r}
otu_set <- rel_abu_error_summary %>% filter(med_inf_error_rate < 10, 
                                            med_inf_error_rate > 8, 
                                            med_inf_error_rate != Inf)
nrow(otu_set)
```

```{r}
count_nb_inferred %>% mutate(prop = count/total_abu) %>% 
    right_join(otu_set) %>% 
      ggplot() + 
      geom_point(aes(x = titration, y = prop)) + 
    geom_line(aes(x = titration, y = exp_prop), color = "darkblue") + 
      geom_line(aes(x = titration, y = inferred_prop), color = "darkorange") + 
      facet_wrap(~feature_id, scales = "free_y") +
      theme_bw() + labs(y = "Relative Abundance", x = "Titration")
```


```{r}
otu_set <- rel_abu_error_summary %>% filter(med_inf_error_rate < 8, 
                                            med_inf_error_rate > 6, 
                                            med_inf_error_rate != Inf)
nrow(otu_set)
```

```{r}
count_nb_inferred %>% mutate(prop = count/total_abu) %>% 
    right_join(otu_set) %>% 
      ggplot() + 
      geom_point(aes(x = titration, y = prop)) + 
    geom_line(aes(x = titration, y = exp_prop), color = "darkblue") + 
      geom_line(aes(x = titration, y = inferred_prop), color = "darkorange") + 
      facet_wrap(~feature_id, scales = "free_y") +
      theme_bw() + labs(y = "Relative Abundance", x = "Titration")
```


```{r}
otu_set <- rel_abu_error_summary %>% filter(med_inf_error_rate < 6, 
                                            med_inf_error_rate > 5, 
                                            med_inf_error_rate != Inf)
nrow(otu_set)
```

```{r}
count_nb_inferred %>% mutate(prop = count/total_abu) %>% 
    right_join(otu_set) %>% 
      ggplot() + 
      geom_point(aes(x = titration, y = prop)) + 
    geom_line(aes(x = titration, y = exp_prop), color = "darkblue") + 
      geom_line(aes(x = titration, y = inferred_prop), color = "darkorange") + 
      facet_wrap(~feature_id, scales = "free_y") +
      theme_bw() + labs(y = "Relative Abundance", x = "Titration")
```


```{r}
otu_set <- rel_abu_error_summary %>% filter(med_inf_error_rate < 2, 
                                            med_inf_error_rate > 1.9, 
                                            med_inf_error_rate != Inf)
nrow(otu_set)
```

```{r}
count_nb_inferred %>% mutate(prop = count/total_abu) %>% 
    right_join(otu_set) %>% 
      ggplot() + 
      geom_point(aes(x = titration, y = prop)) + 
    geom_line(aes(x = titration, y = exp_prop), color = "darkblue") + 
      geom_line(aes(x = titration, y = inferred_prop), color = "darkorange") + 
      facet_wrap(~feature_id, scales = "free_y") +
      theme_bw() + labs(y = "Relative Abundance", x = "Titration")
```


```{r}
otu_set <- rel_abu_error_summary %>% filter(med_inf_error_rate < 1, 
                                            med_inf_error_rate > 0.995, 
                                            med_inf_error_rate != Inf)
nrow(otu_set)
```

```{r}
count_nb_inferred %>% mutate(prop = count/total_abu) %>% 
    right_join(otu_set) %>% 
      ggplot() + 
      geom_point(aes(x = titration, y = prop)) + 
    geom_line(aes(x = titration, y = exp_prop), color = "darkblue") + 
      geom_line(aes(x = titration, y = inferred_prop), color = "darkorange") + 
      facet_wrap(~feature_id, scales = "free_y") +
      theme_bw() + labs(y = "Relative Abundance", x = "Titration")
```

```{r}
high_prop_count <- count_nb_inferred %>% mutate(prop = count/total_abu) %>% 
    group_by(pipe, biosample_id, feature_id) %>% 
    mutate(max_prop = max(prop), min_prop = min(prop)) # %>% filter(min_prop > 0.1)
```

```{r}
high_rel_abu_error <- high_prop_count %>% mutate(prop = count/total_abu,
                             inferred_error = prop - inferred_prop,
                             exp_error = prop - exp_prop,
                             inferred_error_rate = abs(inferred_error)/inferred_prop,
                             exp_error_rate = abs(exp_error)/exp_prop) 
high_rel_abu_error_summary <-rel_abu_error %>% 
    group_by(pipe, biosample_id,feature_id) %>% 
    summarise(med_inf_error_rate = median(inferred_error_rate),
              med_exp_error_rate = median(exp_error_rate))
```

```{r}
high_rel_abu_error_summary %>% 
    ggplot() + geom_boxplot(aes(x = pipe, y = med_inf_error_rate, color = biosample_id)) + scale_y_log10()
```

```{r}
high_rel_abu_error %>% 
    ggplot() + 
    geom_point(aes(x = min_prop, y = abs(inferred_error_rate))) + 
    geom_smooth(aes(x = min_prop, y = abs(inferred_error_rate), color = pipe)) +
    scale_y_log10() + 
    facet_wrap(~pipe)
```


```{r}
high_rel_abu_error %>% 
    ggplot() + 
    geom_point(aes(x = min_prop, y = abs(inferred_error_rate))) + 
    geom_smooth(aes(x = min_prop, y = abs(inferred_error_rate), color = biosample_id)) +
    scale_y_log10() + 
    facet_wrap(~biosample_id, scales = "free_x")
```

```{r}
high_rel_abu_error %>% 
    filter(abs(inferred_error_rate) != Inf) %>% 
    group_by(pipe, biosample_id) %>% 
    summarise(min_error = min(abs(inferred_error_rate)),
              max_error = max(abs(inferred_error_rate)),
              mean_error = mean(abs(inferred_error_rate)),
              median_error = median(abs(inferred_error_rate)),
              lci_error = quantile(abs(inferred_error_rate),0.25),
              uci_error = quantile(abs(inferred_error_rate),0.75))
```


```{r}
rel_abu_error_summary <- high_rel_abu_error %>% 
    filter(abs(inferred_error_rate) != Inf) %>% 
    group_by(pipe, biosample_id) %>% 
    summarise(min_error = min(abs(inferred_error_rate)),
              max_error = max(abs(inferred_error_rate)),
              mean_error = mean(abs(inferred_error_rate)),
              median_error = median(abs(inferred_error_rate)),
              lci_error = quantile(abs(inferred_error_rate),0.25),
              uci_error = quantile(abs(inferred_error_rate),0.75))
```

```{r}
rel_abu_error_summary %>% 
    ggplot() + geom_point(aes(x = biosample_id, y = median_error)) + 
    geom_errorbar(aes(x = biosample_id, ymax = uci_error, ymin = lci_error)) +
    facet_wrap(~pipe)
```


Increase in error with feature relative abundance. Overall noisy .. 
```{r}
rel_abu_error %>% 
    ggplot() + geom_point(aes(x = prop, y = abs(inferred_error), color = t_fctr), alpha = 0.25) + 
    facet_grid(biosample_id~pipe) + scale_x_log10() + scale_y_log10()
```

```{r}
rel_abu_error %>% filter(pipe == "dada2", prop != 0) %>% 
    ggplot() + geom_point(aes(x = prop, y = abs(inferred_error)/prop, color = t_fctr), alpha = 0.25) + 
    facet_grid(t_fctr~biosample_id) + scale_x_log10()# + scale_y_log10()
```

```{r}
rel_abu_error %>% filter(pipe == "dada2", prop != 0, abs(inferred_error)/prop < 10) %>% 
    ggplot() + geom_point(aes(x = prop, y = abs(inferred_error)/prop, color = t_fctr), alpha = 0.25) + 
    facet_grid(t_fctr~biosample_id) + scale_x_log10()# + scale_y_log10()
```


```{r}
rel_abu_error %>% 
    ggplot() + geom_point(aes(x = prop, y = abs(exp_error), color = t_fctr), alpha = 0.25) + 
    facet_grid(biosample_id~pipe) + scale_x_log10() + scale_y_log10()
```

## Species abundance curve
```{r}
mothur_mrexp <- readRDS("~/Projects/mgtst_pipelines/mothur/mothur_mrexp.rds")
mothur_11 <- mothur_mrexp[,which(pData(mothur_mrexp)$biosample_id == "E01JH0011")]
mothur_11 <- mothur_11[,which(pData(mothur_11)$titration %in% c(0))]
mothur_11 <- mothur_11[rowSums(mothur_11) > 1,]

rad_mothur <- mothur_11@assayData$counts %>% rowSums() %>% sads::rad()
rad_df <- rad_mothur %>% as.data.frame() %>% 
      mutate(rel_abund = abund/sum(abund))

ggplot(rad_df) + 
      geom_bar(aes(x = rank, y = rel_abund)) + 
      scale_y_log10(labels = scales::percent) + theme_bw() + 
      labs(x = "OTU Rank", y = "Abundance (%)")
```





## Bac Abundance qPCR data
```{r}
library(ProjectTemplate)
setwd("~/Projects/mgtst_pub/")
load.project()
```

```{r} 
fit_mod_full <- qpcrBacStd %>% 
      filter(!is.na(Ct)) %>% mutate(log_conc = log10(conc)) %>% 
      ## excluding standard curve outlier
      #filter(std != "zymo" | date != "2016-12-09" | conc != 0.00002 | plate != "plate3") %>% 
      group_by(date, std) %>% nest() %>%
      mutate(fit = map(data, .f=~lm(Ct~log_conc ,data = .)), mod = "full")

fit_mod_sub <- qpcrBacStd %>% 
      filter(!is.na(Ct)) %>% mutate(log_conc = log10(conc)) %>% 
      ## excluding standard curve points outside of sample Ct value range
      filter(conc >= 0.2) %>%
      group_by(date, std) %>% nest() %>%
      mutate(fit = map(data, .f=~lm(Ct~log_conc ,data = .)), mod = "sub")      

fit_mod <- bind_rows(fit_mod_full, fit_mod_sub)

fit_list <- fit_mod$fit %>% set_names(paste(fit_mod$date, fit_mod$std, fit_mod$mod))

fit_coefs <-fit_list %>% map_df(coefficients) %>% 
      add_column(coefs = c("intercept","slope")) %>% 
      gather("std","stat",-coefs) %>% spread(coefs, stat)

std_fit <- fit_list %>% map_df(broom::glance, .id = "std") %>% 
      select(std, adj.r.squared) %>% left_join(fit_coefs) %>% 
      separate(std, c("date","std","mod"), sep = " ") %>% 
      mutate(amplification_factor = 10^(-1/slope), 
             efficiency = (amplification_factor - 1) * 100)

mod <- qpcrBacStd %>% 
      filter(std == "shan", conc >= 0.2) %>% mutate(log_conc = log10(conc)) %>% 
      {lm(log_conc~Ct, data = .)}

bac_abu <- qpcrBacAbu %>% filter(!is.na(Ct), std == "shan") %>% add_predictions(mod) %>% 
      mutate(quant = 10^pred) %>% group_by(sample_name) %>% 
      mutate(quant_min = min(quant), quant_max = max(quant))
```

```{r}
sample_name_df <- data_frame(bio_rep = as.character(1:5),
                             biosample_id = paste0("E01JH00",c("04","11","16","17","38")))
bac_abu %>%  
      filter(sample_name != "NTC", Ct < 25) %>% ungroup() %>% 
      mutate(sample_name = gsub(" ","_", sample_name)) %>% 
      separate(sample_name, c("bio_rep","titration"), sep = "_") %>% 
      left_join(sample_name_df) %>%
      mutate(titration = str_replace(titration,"M",""),
            titration = fct_relevel(titration, c("Post",c(1,2,3,4,5,10,15),"Pre"))) %>% 
      ggplot() + 
            geom_point(aes(y = Ct, x = titration)) +
            facet_wrap(~biosample_id, nrow = 1) +
            theme_bw() + labs(x = "Sample Names") 
```

```{r}
bac_ct <- bac_abu %>% filter(sample_name != "NTC", Ct < 25) %>% ungroup() %>% 
      mutate(sample_name = gsub(" ","_", sample_name)) %>% 
      separate(sample_name, c("bio_rep","titration"), sep = "_") %>% 
      left_join(sample_name_df) %>%
      mutate(titration = str_replace(titration,"M",""),
             titration = if_else(titration == "Post","0", titration),
            titration = if_else(titration == "Pre","20", titration),
            titration = fct_relevel(titration, c(0:5,10,15,20)))
      # filter(titration %in% 1:4)
```

```{r}
bac_ct_fit <- bac_ct %>% select(Ct, biosample_id, titration) %>% 
      mutate(titration = as.character(titration) %>% as.numeric(),
             theta = 2^-titration) %>% 
      group_by(biosample_id) %>% nest()
fit <- lm(Ct~theta, bac_ct_fit$data[[1]])
summary(fit)
```
```{r}
fit <- lm(Ct~theta, bac_ct_fit$data[[2]])
summary(fit)
```

```{r}
fit <- lm(Ct~theta, bac_ct_fit$data[[3]])
summary(fit)
```

```{r}
fit <- lm(Ct~theta, bac_ct_fit$data[[4]])
summary(fit)
```

```{r}
fit <- lm(Ct~theta, bac_ct_fit$data[[5]])
summary(fit)
```


```{r}
bac_ct %>% mutate(titration = as.character(titration) %>% as.numeric(),
                  theta = 2^-titration) %>% 
    ggplot() + 
    geom_smooth(aes(x = theta, y = Ct), method = "lm") + 
    geom_point(aes(x = theta, y = Ct)) + 
    facet_wrap(~biosample_id, nrow = 1) + 
    theme_bw() + labs(x = "Theta")
```

```{r}
bac_abu %>%  
      filter(sample_name != "NTC", Ct < 25) %>% 
    ungroup() %>% 
      mutate(sample_name = gsub(" ","_", sample_name)) %>% 
      separate(sample_name, c("bio_rep","titration"), sep = "_") %>% 
      left_join(sample_name_df) %>%
      mutate(titration = str_replace(titration,"M",""),
            titration = fct_relevel(titration, c("Post",c(1,2,3,4,5,10,15),"Pre"))) %>% 
    filter(titration %in% c(1:5,10,15)) %>% 
      ggplot() + 
            geom_point(aes(y = quant, x = titration)) +
            facet_wrap(~biosample_id, nrow = 1) +
            theme_bw() + labs(x = "Titration", y = "Bacteria DNA Concentration (ng/ul)") 
```

